// JavaScript Document

      completeDataSource = [

		{ 'text':'澳门/Macau/MO'},
        { 'text':'台湾/Taiwan/TW'},
        { 'text':'香港/Hongkong/HK'},
		{ 'text':'新加坡/Singapore/SG'},
        { 'text':'阿尔巴尼亚/Albania/AL'},		
        { 'text':'阿尔及利亚/Algeria/DZ'},
		{ 'text':'阿富汗/Afghanistan/AF'},
        { 'text':'阿根廷/Argentina/AR'},
		{ 'text':'阿联酋/United Arad Emirates/AE'},
        { 'text':'阿鲁巴/Aruba/AW'},
		{ 'text':'阿曼/Oman/OM'},
        { 'text':'阿塞拜疆/Azerbaijan/AZ'},
		{ 'text':'埃及/Egypt/EG'},
		{ 'text':'埃塞俄比亚/Ethiopia/ET'},
		{ 'text':'爱尔兰/Ireland, Republic of/ORK'},
		{ 'text':'爱沙尼亚/Estonia/EE'},
		{ 'text':'安道尔/AndorraAD'},
		{ 'text':'安哥拉/Angola/AO'},
		{ 'text':'安圭拉/Anguilla/AI'},
		{ 'text':'安提瓜/Antigua/AG'},
		{ 'text':'奥地利/Austria/AT'},
		{ 'text':'澳大利亚/Australia/AU'},
		{ 'text':'巴巴多斯/Barbados/BB'},
		{ 'text':'巴布亚新几内亚/Papua New Guinea/PG'},
		{ 'text':'巴哈马/Bahamas/BS'},
		{ 'text':'巴基斯坦/Pakistan/PK'},
		{ 'text':'巴拉圭/Paraguay/PY'},
		{ 'text':'巴林/Bahrain/BH'},
		{ 'text':'巴拿马/Panama/PA'},
		{ 'text':'巴西/Brazil/BR'},
		{ 'text':'白俄罗斯/Belarus/BY'},
		{ 'text':'百慕大/Bermuda/BM'},
		{ 'text':'保加利亚/Bulgaria/BG'},
		{ 'text':'贝宁/Benin/BJ'},
		{ 'text':'比利时/Belgium/BE'},
		{ 'text':'冰岛/Iceland/IS'},
		{ 'text':'波多黎各/Puerto Rico/PR'},
		{ 'text':'波兰/Poland/PL'},
		{ 'text':'波斯尼亚和黑塞哥维那/Bosnia & Herzegovina/BSH'},
		{ 'text':'玻利维亚/Bolivia/BO'},
		{ 'text':'伯利兹/Belize/BZ'},
		{ 'text':'伯奈尔/Bonaire/BNR'},
		{ 'text':'博茨瓦那/Botswana/BW'},
		{ 'text':'不丹/Bhutan/BT'},
		{ 'text':'布基纳法索/Burkina Faso/BF'},
		{ 'text':'布隆迪/Burundi/BI'},
		{ 'text':'朝鲜/ Korea, D.P.R.of/KP'},
		{ 'text':'赤道几内亚/Equatorial Guinea/GQ'},
		{ 'text':'大溪地/Tahiti/TP'},
		{ 'text':'丹麦/Demark/DK'},
		{ 'text':'德国/Germany/DE'},     
		{ 'text':'东帝汶/East Timor/ETM'},
		{ 'text':'多哥/Togo/TG'},
		{ 'text':'多米尼加/Dominica/DM'},
		{ 'text':'多米尼加共和国/Dominican Republic/DO'},  
		{ 'text':'俄罗斯/Russian Federation/RU'},
		{ 'text':'厄瓜多尔/Ecuador/EC'},
		{ 'text':'厄立特里亚/Eritrea/ER'},
		{ 'text':'法国/France/FR'},   
		{ 'text':'法罗群岛/Faroe Islands/FO'},
		{ 'text':'法属波利尼西亚/French Polynesia/FP'},
		{ 'text':'法属圭亚那/French Guiana/GF'},
		{ 'text':'菲律宾/Philipines, The/PH'},  
		{ 'text':'斐济群岛/Fiji Islands/FJ'},
		{ 'text':'芬兰/Finland/FI'},
		{ 'text':'佛得角/Cape Verde/CPV'},
		{ 'text':'福克兰群岛/Falkland Islands/FK'},  
		{ 'text':'冈比亚/Gambia/GM'},
		{ 'text':'刚果/Congo/CG'},
		{ 'text':'刚果民主共和国/Congo, The Democratic Republic/CGO'},
		{ 'text':'哥伦比亚/Colombia/CO'}, 
		{ 'text':'哥斯达黎加/Costa Rica/CR'},
		{ 'text':'格林纳达/Grenada/GD'},
		{ 'text':'格陵兰岛/Greenland/GL'},
		{ 'text':'格鲁吉亚/Georgia/GE'},
		{ 'text':'根西岛/Guernsey/GCI'},
		{ 'text':'古巴/Cuba/CU'},
		{ 'text':'瓜德罗普/Guadeloupe/GP'},
		{ 'text':'关岛/Guam/GU'},
		{ 'text':'圭亚那/Guyana(British)/GY'},
		{ 'text':'哈萨克斯坦/Kazakhstan/KZ'},
		{ 'text':'海地/Haiti/HT'},
		{ 'text':'韩国/Korea, Republic of/KR'},    
		{ 'text':'荷兰/Netherlands/NL'},
		{ 'text':'洪都拉斯/Honduras/HN'},
		{ 'text':'基里巴斯/Kiribati/KI'},
		{ 'text':'吉布提/Djibouti/DJ'},
		{ 'text':'吉尔吉斯斯坦/Kyrgyzstan/KG'},
		{ 'text':'几内亚/Guinea Republic/GN'},
		{ 'text':'几内亚比绍/Guinea-Bissau/GW'},
		{ 'text':'加拿大/Canada/CA'},
		{ 'text':'加那利群岛/Canary Islands/CNR'},
		{ 'text':'加纳/Ghana/GH'},
		{ 'text':'加蓬/Gabon/GA'},
		{ 'text':'柬埔寨/Cambodia (Kampuchea)/KH'},
		{ 'text':'捷克共和国/Czech Republic/CZ'},
		{ 'text':'津巴布韦/Zimbabwe/ZW'},
		{ 'text':'喀麦隆/Cameroon/CM'},
		{ 'text':'卡塔尔/Qatar/QA'},
		{ 'text':'开曼群岛/Cayman Islands/KY'},
		{ 'text':'科摩罗/Comoros/KM'},
		{ 'text':'科特迪瓦/Cote D\'lvoire/IV'},
		{ 'text':'科威特/Kuwait/KW'},
		{ 'text':'克罗地亚/Croatia/HR'},
		{ 'text':'肯尼亚/Kenya/KE'},
		{ 'text':'库克群岛/Cook Islands/CK'},
		{ 'text':'库拉索/Curacao/CUR'}, 
		{ 'text':'拉脱维亚/Latvia/LV'},
		{ 'text':'莱索托/Lesotho/LS'},
		{ 'text':'老挝/Laos/LA'},
		{ 'text':'黎巴嫩/Lebanon/LB'},   
		{ 'text':'立陶宛/Lithuania/LT'},
		{ 'text':'利比里亚/利比里亚	Liberia/LR'},
		{ 'text':'利比亚/Libya/LY'},
		{ 'text':'列支敦士登/Liechtenstein/LI'},
		{ 'text':'留尼旺岛/Renuion, Island of/RNI'},
		{ 'text':'卢森堡/Luxembourg/LU'},
		{ 'text':'卢旺达/Rwanda/RW'},
		{ 'text':'罗马尼亚/Romania/RO'},   
		{ 'text':'马达加斯加/Madagascar/MG'},
		{ 'text':'马尔代夫/Maldives/MV'},
		{ 'text':'马耳他/Malta/MT'},
		{ 'text':'马拉维/Malawi/MW'},
		{ 'text':'马来西亚/Malaysia/MY'},
		{ 'text':'马里/Mali/ML'},
		{ 'text':'马其顿/Macedonia/MK'},   
		{ 'text':'马绍尔群岛/Marshall Islands/MH'},
		{ 'text':'马提尼克/Martinique/MTN'},
		{ 'text':'毛里求斯/Mauritius/MU'},
		{ 'text':'毛里塔尼亚/Mauritania/MR'},
		{ 'text':'美国/United States of America/US'},
		{ 'text':'美属萨摩亚/American Samoa/USSM'},
		{ 'text':'美属维尔京群岛/Virgin Islands (U.S.)/VI'},   
		{ 'text':'蒙古/Mongolia/MN'},
		{ 'text':'蒙特塞拉岛/Montserrat/MS'},
		{ 'text':'孟加拉/Bangladesh/BD'},
		{ 'text':'秘鲁/Peru/PE'},
		{ 'text':'缅甸/Myanmar/MM'},
		{ 'text':'摩尔多瓦/Moldova, Republic of/MD'},
		{ 'text':'摩洛哥/Morocco/MA'},   
		{ 'text':'摩纳哥/Monaco/MC'},
		{ 'text':'莫桑比克/Mozambique/MZ'},
		{ 'text':'墨西哥/Mexico/MX'},
		{ 'text':'纳米比亚/Namibia/NA'},
		{ 'text':'南非/South Africa/ZA'},
		{ 'text':'瑙鲁/Nauru, Republic of/NR'},
		{ 'text':'尼泊尔/Nepal/NP'},   
		{ 'text':'尼加拉瓜/Nicaragua/NI'},
		{ 'text':'尼日尔/Niger/NE'},
		{ 'text':'尼日利亚/Nigeria/NG'},
		{ 'text':'尼维斯/Nevis/NV'},
		{ 'text':'纽埃岛/Niue/NU'},
		{ 'text':'挪威/Norway/NO'},
		{ 'text':'葡萄牙/Portugal/PT'},   
		{ 'text':'日本/Japan/JP'},
		{ 'text':'瑞典/Sweden/SE'},
		{ 'text':'瑞士/Switzerland/CH'},
		{ 'text':'萨尔瓦多/El Salvador/SV'},
		{ 'text':'萨摩亚/Samoa/AS'},
		{ 'text':'塞班岛/Saipan/SP'},
		{ 'text':'塞尔维亚和黑山/Serbia and Montenegro/CS'},   
		{ 'text':'塞拉利昂/Sierra Leone/SL'},
		{ 'text':'塞内加尔/Senegal/SN'},
		{ 'text':'塞浦路斯/Cyprus/CY'},
		{ 'text':'塞舌尔/Seychelles/SC'},
		{ 'text':'沙特阿拉伯/Saudi Arabia/SA'},
		{ 'text':'圣巴夫林米/St Barthelemy/SBT'},
		{ 'text':'圣多美和普林西比/Sao Tome and Principe/ST'},   
		{ 'text':'圣基茨/St Kitts/SKT'},
		{ 'text':'圣卢西亚岛/St Lucia/LC'},
		{ 'text':'圣马丁/St Maarten/SMT'},
		{ 'text':'圣文森特岛/St Vincent/VC'},
		{ 'text':'圣尤斯达求斯/St Eustatius/SET'},
		{ 'text':'斯里兰卡/Sri Lanka/LK'},
		{ 'text':'斯洛伐克/Slovakia/SK'},   
		{ 'text':'斯洛文尼亚/Slovenia/SI'},
		{ 'text':'斯威士兰/Swaziland/SZ'},
		{ 'text':'苏丹/Sudan/SD'},
		{ 'text':'苏里南/Suriname/SR'},
		{ 'text':'所罗门群岛/Soloman Islands/SB'},
		{ 'text':'索马里/Somalia/SO'},
		{ 'text':'索马里兰/Somaliland, Rep of (North Somalia)/SML'},   
		{ 'text':'塔吉克斯坦/Tajikistan/TJ'},
		{ 'text':'泰国/Thailand/TH'},
		{ 'text':'坦桑尼亚/Tanzania/TZ'},
		{ 'text':'汤加/Tonga/TO'},
		{ 'text':'特克斯和凯科斯群岛/Turks And Caicos Islands/TCS'},
		{ 'text':'特立尼达和多巴哥/Trinidad and Tobago/TT'},
		{ 'text':'突尼斯/Tunisia/TN'},   
		{ 'text':'图瓦卢/Tuvalu/TV'},
		{ 'text':'土耳其/Turkey/TR'},
		{ 'text':'土库曼斯坦/Turkmeinistan/TM'},
		{ 'text':'瓦努阿图/Vanuatu/VU'},
		{ 'text':'危地马拉/Guatemala/GT'},
		{ 'text':'委内瑞拉/Venezuela/VE'},
		{ 'text':'文莱/Brunei/BN'},   
		{ 'text':'乌干达/Uganda/UG'},
		{ 'text':'乌克兰/Ukraine/UA'},
		{ 'text':'乌拉圭/Uruguay/UY'},
		{ 'text':'乌兹别克斯坦/Uzbekistan/UZ'},
		{ 'text':'西班牙/Spain/ES'},
		{ 'text':'希腊/Greece/GR'},
		{ 'text':'新喀里多尼亚/New Caledonia/NC'},   
		{ 'text':'新西兰/New Zealand/NZ'},
		{ 'text':'匈牙利/Hungary/HU'},
		{ 'text':'叙利亚/Syria/SY'},
		{ 'text':'牙买加/Jamaica/JM'},
		{ 'text':'亚美尼亚/Armenia/AM'},
		{ 'text':'也门/Yemen/YE'},
		{ 'text':'伊拉克/Iraq/IQ'},   
		{ 'text':'伊朗/Iran, Islamic Republic of/IR'},
		{ 'text':'以色列/Israel/IL'},
		{ 'text':'意大利/Italy/IT'},
		{ 'text':'印度/India/IN'},
		{ 'text':'印度尼西亚/Indonesia/ID'},
		{ 'text':'英国/United Kingdom/GB'},
		{ 'text':'英属维尔群岛/Virgin Islands (British)/GBVG'},   
		{ 'text':'约旦/Jordan/JO'},
		{ 'text':'越南/Vietnam/VN'},
		{ 'text':'赞比亚/Zambia/ZM'},
		{ 'text':'泽西岛/Jersey/JE'},
		{ 'text':'乍得/Chad/TD'},
		{ 'text':'直布罗陀/Gibraltar/GI'},
		{ 'text':'智利/Chile/CL'},   
		{ 'text':'中非共和国/Central African Republic/CF'}


      ];
      
      var autoComplete = null;
      onload = function pageLoadHdle() {
        var configuration = {
          instanceName: "autoComplete",
          textbox: document.getElementById("cdes"),
          dataSource: completeDataSource
        };

        autoComplete = new neverModules.modules.autocomplete(configuration);
        autoComplete.useContent = true;
		autoComplete.useSpaceMatch = true;
		autoComplete.ignoreWhere = true;
        autoComplete.create();
        //autoComplete.expandAllItem();

  /*      autoComplete.showAnimateImage("images/indicator.gif");

        window.setTimeout(
          function closeAnimateImageAfter1seconds() { 
            autoComplete.closeAnimateImage();
          }, 1000);*/
      }

